//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPECB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Department { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public long Id { get; set; }
    }
}
